import json
import time

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from backend.config import settings
from backend.graph.state import AgentState

_llm = ChatOpenAI(
    model="deepseek-chat",
    api_key=settings.DEEPSEEK_API_KEY,
    base_url="https://api.deepseek.com",
    temperature=0.3,
)

_prompt = ChatPromptTemplate.from_template(
    """You are the Executor Agent for OpsMind AI. Generate a professional operations report in Markdown.

User Request: {user_query}
Goal: {goal}
KPI Insights: {insights}
Identified Risks: {risks}
Approved Recommendations: {recommendations}

Generate a complete structured report:

# Weekly Operations Report

## Executive Summary
[2-3 sentence overview of current state]

## Key Performance Indicators
| Metric | Value |
|--------|-------|
[Table with KPI data from insights]

## Risk Analysis
[For each risk: project name, risk level, root cause, recommended action]

## Approved Action Plan
[Numbered list of approved recommendations with owner and timeline]

## Next Steps
[3 immediate actions for this week]

---
*Generated by OpsMind AI | {goal}*"""
)

chain = _prompt | _llm | StrOutputParser()


async def executor_node(state: AgentState) -> dict:
    start = time.time()
    result = await chain.ainvoke({
        "user_query": state["user_query"],
        "goal": state["goal"],
        "insights": json.dumps(state.get("insights", {}), indent=2),
        "risks": json.dumps(state.get("risks", []), indent=2),
        "recommendations": json.dumps(state.get("recommendations", []), indent=2),
    })
    latency = int((time.time() - start) * 1000)
    log = {"agent": "executor", "latency_ms": latency, "output": {"report_length": len(result)}}
    return {
        "execution_result": result,
        "status": "completed",
        "agent_logs": state.get("agent_logs", []) + [log],
    }
